<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VpuSimulator.Application\VpuSimulator.Application.csproj" />
    <ProjectReference Include="..\VpuSimulator.Domain\VpuSimulator.Domain.csproj" />
    <ProjectReference Include="..\VpuSimulator.Rules\VpuSimulator.Rules.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.104.1" />
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="MassTransit" Version="9.2.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Polly" Version="8.8.0" />
  </ItemGroup>

</Project>
